---
name: Publish
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  main:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: >-
          echo "::set-output
            name=version::$(grep -m1 IMAGEMAGICK_VERSION Dockerfile |
            awk -F= '{print $2}')"
        id: version
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        id: docker
        with:
          images: |
            mfinelli/imagemagick
            ghcr.io/mfinelli/imagemagick
          tags: type=semver,pattern={{version}}
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            mfinelli/imagemagick:${{ steps.version.outputs.version }}
            mfinelli/imagemagick:latest
            ghcr.io/mfinelli/imagemagick:${{ steps.version.outputs.version }}
            ghcr.io/mfinelli/imagemagick:latest
      - uses: peter-evans/dockerhub-description@v3
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfinelli/imagemagick
          short-description: ${{ github.event.repository.description }}
      - uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
